import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://thinking-tester-contact-list.herokuapp.com/');
  await expect(page.getByRole('heading', { name: 'Contact List App' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await expect(page.getByRole('textbox', { name: 'Email' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Password' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Submit' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Sign up' })).toBeVisible();

  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('vonwebster.saikou@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('pass123');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email' }).fill('vonwebster@gmail.com');
  await page.getByRole('button', { name: 'Submit' }).click();

  await expect(page.getByRole('heading', { name: 'Contact List' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Add a New Contact' })).toBeVisible();
  await page.getByRole('button', { name: 'Add a New Contact' }).click();
  
  await expect(page.getByRole('heading', { name: 'Add Contact' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: '* First Name:' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: '* Last Name:' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Date of Birth:' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Email:' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Phone:' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Street Address 1:' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Street Address 2:' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'City:' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'State or Province:' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Postal Code:' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Country:' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Submit' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Cancel' })).toBeVisible();
  await page.getByRole('textbox', { name: '* First Name:' }).click();
  await page.getByRole('textbox', { name: '* First Name:' }).fill('Jimmy');
  await page.getByRole('textbox', { name: '* Last Name:' }).click();
  await page.getByRole('textbox', { name: '* Last Name:' }).fill('Neutron');
  await page.getByRole('textbox', { name: 'Date of Birth:' }).click();
  await page.getByRole('textbox', { name: 'Date of Birth:' }).fill('2025-06-20');
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('jimmy@neutron.com');
  await page.getByRole('textbox', { name: 'Phone:' }).click();
  await page.getByRole('textbox', { name: 'Phone:' }).fill('123456000');
  await page.getByRole('textbox', { name: 'Street Address 1:' }).click();
  await page.getByRole('textbox', { name: 'Street Address 1:' }).fill('Retroville');
  await page.getByRole('textbox', { name: 'Street Address 2:' }).click();
  await page.getByRole('textbox', { name: 'Street Address 2:' }).fill('Abcdef');
  await page.getByRole('textbox', { name: 'City:' }).click();
  await page.getByRole('textbox', { name: 'City:' }).fill('Cityville');
  await page.getByRole('textbox', { name: 'State or Province:' }).click();
  await page.getByRole('textbox', { name: 'State or Province:' }).fill('Statious');
  await page.getByRole('textbox', { name: 'Postal Code:' }).click();
  await page.getByRole('textbox', { name: 'Postal Code:' }).fill('123 code');
  await page.getByRole('textbox', { name: 'Country:' }).click();
  await page.getByRole('textbox', { name: 'Country:' }).fill('USA');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Postal Code:' }).click();
  await page.getByRole('textbox', { name: 'Postal Code:' }).fill('123');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('cell', { name: 'Jimmy Neutron' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '-06-20' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'jimmy@neutron.com' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '123456000' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Retroville Abcdef' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Cityville Statious' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'USA' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Logout' })).toBeVisible();
  await page.getByRole('button', { name: 'Logout' }).click();
});